CREATE TABLE IF NOT EXISTS receptai(
    id SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
    pavadinimas VARCHAR(50) NOT NULL,
    kaina DECIMAL(4, 2) NOT NULL,
    nurodymai VARCHAR(300),
    PRIMARY KEY(id)
) ENGINE = INNODB;